remove method added + tests
nosmokingsurfer/FSE_Lab_Version_Control pull request #4
Opened 2020-10-04 19:34 UTC by nosmokingsurfer

2020-10-04 23:14 UTC, ElviraPlumite requested changes

2020-10-04 23:14 UTC, eplumite commented on storage.py
>          pass
This line needs to be deleted because _pass_ is useful in places where your code will eventually go, but has not been written yet.

2020-10-04 23:14 UTC, eplumite commented on tests.py
>      pass
This line needs to be deleted.

2020-10-04 23:14 UTC, eplumite commented on storage.py
> +            raise KeyError("Key %s does not exist" % key)
You just reimplemented the behavior of function del. If key exists, it deletes key and raises error otherwise.
```
>>> a = {'one': 1}
>>> del a['one']
>>> del a['one']
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
KeyError: 'one'
```
The only reason to use this construction is custom error message. Did you actually mean this?

2020-10-04 23:14 UTC, eplumite commented on tests.py
> +        test = Storage(data)
Name _test_ seems a bit confusing: function name is very similar. Moreover, it doesn't provide straight assumption of which type variable has. May be it's worth using _st_ as it was used in function _test_get()_ of something like that?

2020-10-04 23:14 UTC, ElviraPlumite commented on tests.py
> +        test.remove("one")
It's a good idea to follow rule that each test function should cover only one test-case: 'remove existed key' OR 'remove absent key'.

In line 11 you used dictionary _data_ to assign variable _test_. In python mutable variables are passed by reference that's why key "one" exists in variable _test_ after changing value of _data_ in line 22. 

But you can't be 100% sure that your _test_ variable is valid after executing first block (lines 8-17): some links can be crashed or smth else. May be it's better to implement different functions to test different behavior.

2020-10-04 23:14 UTC, ElviraPlumite commented on tests.py
> +    #test_add()
This line shouldn't be commented.

2020-10-04 23:14 UTC, ElviraPlumite commented on tests.py
> +    #test_set()
This line shouldn't be commented.

2020-10-05 05:34 UTC, NevVerVer approved these changes
Approve

2020-10-05 06:03 UTC, nosmokingsurfer commented on storage.py
> +            raise KeyError("Key %s does not exist" % key)
Yes, I just wanted to learn how to raise an exceptions with custom messages.

2020-10-05 06:06 UTC, nosmokingsurfer commented on storage.py
>          pass
ok

2020-10-05 06:08 UTC, nosmokingsurfer commented on tests.py
>      pass
ok

2020-10-05 06:08 UTC, nosmokingsurfer commented on tests.py
> +    #test_set()
done

2020-10-05 06:24 UTC, nosmokingsurfer reviewed
@ElviraPlumite fixed the problems. Please review.

2020-10-05 06:24 UTC, nosmokingsurfer commented on tests.py
> +        test = Storage(data)
agree

2020-10-05 06:43 UTC, ElviraPlumite approved these changes
Approved.

2020-10-05 06:52 UTC, merged